- examples/vitess/README.md
- examples/vitess/hooks/etcd.libsonnet
- examples/vitess/hooks/k8s.libsonnet
- examples/vitess/hooks/metacontroller.libsonnet
- examples/vitess/hooks/sync-cell.jsonnet
- examples/vitess/hooks/sync-cluster.jsonnet
- examples/vitess/hooks/sync-keyspace.jsonnet
- examples/vitess/hooks/sync-shard.jsonnet
- examples/vitess/hooks/vitess.libsonnet
- examples/vitess/hooks/vtctlclient.libsonnet
- examples/vitess/hooks/vtctld.libsonnet
- examples/vitess/hooks/vtgate.libsonnet
- examples/vitess/hooks/vttablet.libsonnet
- examples/vitess/my-vitess.yaml
- examples/vitess/test/k8s_test.jsonnet
- examples/vitess/test/vitess_test.jsonnet
- examples/vitess/update-hooks.sh
- examples/vitess/vitess-operator.yaml
This is still a work in progress, but cluster startup works.
Next steps:
cc @derekperkins
This is an example of an app-specific [Operator](https://coreos.com/operators/), in this case for [Vitess](http://vitess.io), built with Metacontroller.
It's meant to demonstrate the following patterns:
* Building an Operator for a complex, stateful application out of a set of small Lambda Controllers that each do one thing well.
* Replacing static, client-side template rendering with Lambda Controllers, which can adjust based on dynamic cluster state.
* Using a functional-style language ([Jsonnet](http://jsonnet.org)) to define Lambda Controllers in terms of template-like transformations on JSON objects.
* Using the "Apply" update strategy feature of CompositeController, which emulates the behavior …
> [WIP] Vitess Operator example

- dynamic/clientset/dynamic_clientset.go
- dynamic/discovery/discovery.go
- main.go
For now, it's just polling at a fixed interval that's larger than the controller sync interval. It's also now in the background, so controllers don't have to wait for the discovery refresh every time before syncing.
If necessary, we can consider latency improvements in the future, such as refreshing on a cache miss or watching for new CRDs to become Established.
Closes #4
> Cache API discovery info.

- examples/catset/README.md
- examples/catset/catset-controller.yaml
- examples/catset/sync.js
This enables the new rolling update feature (#21) for the CatSet example, so it's now a more complete replacement for StatefulSet.
> examples/catset: Add StatefulSet-style rolling update.

- examples/vitess/hooks/metacontroller.libsonnet
- examples/vitess/hooks/sync-cell.jsonnet
- examples/vitess/hooks/sync-shard.jsonnet
- examples/vitess/hooks/vtctlclient.libsonnet
- examples/vitess/hooks/vttablet.libsonnet
- examples/vitess/vitess-operator.yaml
For now, tablet rollouts (part of the VitessShard controller) work similarly to StatefulSet updates. In a later PR, I plan to add rollout hooks that will allow for planned reparenting before updating the master tablet.
cc @derekperkins
> examples/vitess: Enable rolling updates.

- README.md
- controller/composite/child_map.go
- controller/composite/controller.go
- controller/composite/metacontroller.go
- controller/composite/rolling_update.go
- dynamic/informer/factory.go
- dynamic/informer/informer.go
- dynamic/lister/lister.go
- main.go
This adds a dynamic shared informer factory and uses it in CompositeController so we no longer poll the API server on every sync.
All CompositeControllers share a single watch stream for each (apiVersion, resource) pair. For example, a single Metacontroller instance might host many controllers that watch Pods, but there will only be one stream of Pod events from the API server to Metacontroller.
The watch stream for a given resource is only started when the first controller requests it, and is stopped when no more controllers need it. Controllers can watch any arbitrary resource, including custom resources.
In addition to reducing load on the API server, this also makes CompositeControllers much more responsive. No changes are needed for existing hooks to benefit from this.
Closes #6 …
> Use dynamic shared informers instead of polling.

- controller/decorator/controller.go
The deferred cleanup function needs access to the original `c`, not the value passed to `return` (which is `nil` in the case of an error).
Fixes #39
> Fix panic in DecoratorController.

- Gopkg.lock
- Gopkg.toml
to avoid flux in api changes in k8s, pin to release versions of k8s deps.
> pint to 1.9.1 k8s release dependency

- Dockerfile.dev
- Gopkg.lock
- Makefile
- docs/_contrib/build.md
- kustomization.yaml
- manifests/dev/args.yaml
- manifests/dev/image.yaml
- manifests/metacontroller.yaml
- skaffold.yaml
This lets us keep the files in `manifests/` pinned to release tags and non-debug args.
> Add Skaffold+Kustomize config for development.

- apis/metacontroller/v1alpha1/types.go
- docs/_api/compositecontroller.md
- docs/_api/decoratorcontroller.md
- docs/_api/hook.md
- hooks/webhook.go
Fixes #54
- User defined timeout for sync webhooks, defaults to current behavior.
- Documentation.
_Note that I have not tested this PR as I'm still figuring out how to setup the build environment properly._
> Add user-defined webhook timeout

- .dockerignore
Ignoring things that aren't needed to build the Docker image helps Skaffold know when not to rebuild the image.
> Add .dockerignore file.

- dynamic/lister/lister.go
Lister can get cluster scoped resources with name.
Fixes #61
> dynamic/lister: Get cluster scoped resources with name

- docs/_guide/install.md
- examples/bluegreen/test.sh
- examples/catset/test.sh
- examples/indexedjob/test.sh
- manifests/dev/args.yaml
- manifests/dev/image.yaml
- manifests/metacontroller.yaml
Addressing issue #5 partially. In the long run, we still have to resolve leader election issue when the user spawns more than one Metacontroller instance.
Metacontroller uses `apps/v1beta1 Deployment` under the hood. This PR changes the Metacontroller to use `apps/v1beta2 StatefulSet` to maintain the invariant of only one Metacontroller instance is active at a time.
> only allow one Metacontroller instance to be active at a time

- Dockerfile
- Dockerfile.dev
This CL updates both the `Dockerfile` and `Dockerfile.dev` to install
the `ca-certificates` package in the final docker image.
closes: #86
> install ca-certificates in docker image

- Gopkg.lock
- Gopkg.toml
- main.go
This CL adds an http endpoint with one handler "/metrics" that serves
Prometheus metrics exported by MetaController. The metrics are collected
using OpenCensus and exported using the Prometheus HTTP exposition
format.
This CL also configures the Kubernetes workqueue package to collect its
statistics and expose them via the Prometheus http endpoint. We collect
and expose all of the workqueue metrics (Depth, Adds, Latency,
WorkDuration, Retries) tagged with the name of the queue.
> Expose workqueue stats

- docs/_guide/create.md
CRD helloworlds.example.com spec needs 'scope' on spec. without scope:
`error: error validating "crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false
`
> add scope on crd spec from guide / Create a Controller

- controller/common/common.go
- controller/common/manage_children.go
- controller/composite/controller.go
- dynamic/clientset/clientset.go
- dynamic/controllerref/unstructured.go
- dynamic/discovery/discovery.go
The main goal is to remove the duplication caused by introducing `NamespacedResourceClient`, because I want to add more methods similar to UpdateWithRetries as part of the work on finalizers, and I don't want to have to make extra wrappers for every new method.
We introduced `NamespacedResourceClient` to preserve the expected semantic from the generated clients that you can't chain calls to `.Namespace()`. However, given the dynamic nature of ResourceClient, I think it's simpler if we just keep the one type and allow chaining.
As part of that, I added a check that makes calling `.Namespace()` revert to a cluster-scoped client if the given namespace is empty, or if we know from discovery info that the resource is cluster-scoped. This makes it safer to just always call `Namespace()` …
> Simpify ResourceClient namespace handling.

- Dockerfile
- Dockerfile.dev
Install packages before copying in the new binary, so it doesn't reinstall
the packages every time the binary changes.
> Dockerfile: Improve use of cached layers during rebuild.

- Gopkg.lock
- controller/common/manage_children.go
- controller/composite/controller.go
- dynamic/clientset/clientset.go
- dynamic/discovery/discovery.go
- examples/bluegreen/bluegreen-controller.yaml
- examples/bluegreen/test.sh
- examples/catset/catset-controller.yaml
- examples/indexedjob/indexedjob-controller.yaml
Closes #26
Items achieved:
1. added an `AtomicUpdateStatus` that calls `Update()` or `UpdateStatus` based on existence of status subresource
2. added a `.subresources` field for `APIResource` to record all subresources of a given resource (not just status subresource)
3. added a `HasSubresource` function for `APIResource` to determine whether a subresource exists
4. revert `.status` field for `ApplyUpdate()`
All smoke tests pass in latest commit.
> Support status subresource and ObservedGeneration

- Gopkg.lock
- main.go
This allows Metacontroller and webhook servers to run outside the Kubernetes cluster that they manage. However, CompositeController or DecoratorController objects still live in the same cluster as the objects being managed.
This should help unblock experimentation with out-of-cluster hosting patterns like the ones discussed in #111.
> Add flag to configure client for remote API server.

- .gitignore
- controller/decorator/controller.go
- controller/decorator/hooks.go
- docs/_api/decoratorcontroller.md
- examples/status/README.md
- examples/status/my-noop.yaml
- examples/status/noop-controller.yaml
- examples/status/sync.js
- examples/status/test.sh
In order to be consistent with CompositeController the status returned by the hook replaces the existing one
> Add status as part of DecoratorController hook response

- kustomization.yaml
- manifests/dev/kustomization.yaml
- skaffold.yaml
This allows Kustomize users to refer to Metacontroller's base
kustomization by URL, either for installation:
$ kustomize build github.com/GoogleCloudPlatform/metacontroller?ref=v0.4.0 | kubectl apply -f -
Or as a base in their own overlays:
```yaml
bases:
- github.com/GoogleCloudPlatform/metacontroller?ref=v0.4.0
```
(P.S. Thanks for Metacontroller!!)
> Split dev kustomization into base + dev overlay

- controller/composite/controller.go
Bugfix for observed behavior where CompositeController finalizers do not run, in kubernetes v1.10.8.
The `updateParentObject()` method ignores updates when the resource version and spec haven't changed.  However, `kubectl delete` , when finalizers are present, will add `deletionTimestamp`, but will not modify the resource version or the spec.   So finalizers do not run.
This PR changes `updateParentObject()` to always process updates if they contain a deletion timestamp, so that the finalizers run.
Fixes #125
> bugfix for finalizers to run

- controller/common/manage_children.go
Fixes #127.
I tried a build with this change in my cluster, and it was able to delete a pod created on behalf of a cluster-scoped composite controller.
> Fix deleting a ns-scoped child of a cluster-scoped controller

- manifests/metacontroller-rbac.yaml
- manifests/metacontroller.yaml
`rbac.authorization.k8s.io` went v1 in K8s v1.8, StatefulSet in 1.9
> Update apiVersions to v1

- controller/composite/controller.go
- controller/decorator/controller.go
- examples/clusteredparent/test.sh
Previously, we could assume that parent and child were always in the
same namespace. Now that we support cluster-scoped parents with
namespaced children, we need to take that into account when resolving
controllerRefs (mapping a child to its parent) and when fetching
children for a given parent.
Fixes #131
> Fix parent-child lookup for cluster-scoped parents.

- .gitignore
- .travis.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
- controller/composite/controller_revision.go
- controller/composite/hooks.go
- controller/decorator/controller.go
- controller/decorator/hooks.go
- docs/_contrib/build.md
- hack/get-kube-binaries.sh
- main.go
- server/server.go
- test/integration/composite/composite_test.go
- test/integration/framework/apiserver.go
- test/integration/framework/crd.go
- test/integration/framework/etcd.go
- test/integration/framework/fixture.go
- test/integration/framework/main.go
- test/integration/framework/metacontroller.go
- test/integration/framework/webhook.go
This adds a framework for integration tests that run against a bare kube-apiserver with no other Kubernetes components (i.e. no kubelets). Unlike the end-to-end tests in `examples/`, these integration tests don't require an actual Kubernetes cluster. This allows efficient testing of Metacontroller behavior at the level of its interaction with Kubernetes API objects, after which the respective implementations of those APIs are assumed to work.
This also includes the first sample test, which exercises a simple CompositeController sync webhook scenario to validate the test framework. Additional tests will be added in separate PRs.
> Add integration test framework and sample test.

- manifests/metacontroller-rbac.yaml
- manifests/namespace.yaml
Allows `kubectl apply -f manifests/` to create all required resources, including a `metacontroller` Namespace.
However, `kustomization.yaml` does not include that manifest in its `resources`, which lets kustomize handle namespace creation.
Replaces my borked #129.
> Move namespace to own manifest

- kustomization.yaml
This changes the `app` label to `app.kubernetes.io/name` as [recommended](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) by SIG-Apps.
I'll likely quiet down after this 😄
> Change app label

- test/integration/decorator/decorator_test.go
- test/integration/framework/apiserver.go
- test/integration/framework/fixture.go
- test/integration/framework/main.go
- test/integration/framework/metacontroller.go
This is a skeleton for DecoratorController integration tests, just like the one for CompositeController. This also fixes the test framework so integration tests can run in parallel.
> Add basic integration test for DecoratorController.

- controller/common/manage_children.go
- test/integration/composite/composite_test.go
- test/integration/decorator/decorator_test.go
- test/integration/framework/crd.go
- test/integration/framework/fixture.go
- test/integration/framework/main.go
- test/integration/framework/metacontroller.go
For most API types, the server-side default (when the client doesn't specify) is cascading deletion, meaning that the GC will clean up children owned by the object being deleted. For some legacy APIs like Job that went GA before the server-side GC was added, the default is instead orphaning, to maintain backwards compatibility.
Now that server-side cascading deletion (GC) is the norm, users expect it to happen uniformly. Therefore, we should explicitly request cascading deletion whenever we delete children in Metacontroller, in case the server-side default is different for legacy reasons.
Fixes #145
> Always delete children with cascading deletion.

- controller/common/common.go
- controller/composite/controller.go
- controller/composite/controller_revision.go
- controller/composite/hooks.go
- controller/composite/rolling_update.go
- controller/decorator/controller.go
- controller/decorator/hooks.go
- docs/_api/compositecontroller.md
- docs/_api/decoratorcontroller.md
- test/integration/composite/composite_test.go
- test/integration/decorator/decorator_test.go
- test/integration/framework/metacontroller.go
This adds a `resyncAfterSeconds` field (can be a decimal) to the `sync` hook response of CompositeController and DecoratorController. This field allows the hook response to request a resync of one particular object after a specified delay, for example if the hook knows it wants to recheck some external state for just that object. As a result, the controller-wide resyncPeriodSeconds can be kept at a
larger interval while being responsive when external state is more likely to change quickly for certain objects.
Closes #152
> Add per-object, one-time resync.
